light:
  - platform: mqtt
    name: "Coffee"
    state_topic: "home/kitchen/coffee_state"
    command_topic: "home/kitchen/coffee_payload"
    brightness_state_topic: "home/kitchen/coffee_brightness"
    brightness_command_topic: "home/kitchen/coffee_brightness"
    brightness_scale: 100
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    retain: true
